server:
  port: 8081

database:
  host: localhost
  port: 5432
  dbname: governance
  sslmode: disable

proposal:
  number_records: 50
  time_request: 10 # секунды

kafka:
  address: localhost
  port: 9092
