server:
  port: 8081

database:
  host: db-postgres
  port: 5434
  dbname: governance
  sslmode: disable

proposal:
  number_records: 5
  time_request: 10 # секунды

kafka:
  address: kafka
  port: 29092
